import Head from "next/head";

export default function integracao() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="vermelha">Texto #01</div>
        <div className="azul">Texto #02</div>
      </div>
    </>
  );
}
